"""add_report_minute_column

Revision ID: 29301a8d8411
Revises:
Create Date: 2026-01-19 20:14:45.687351

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '29301a8d8411'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_hour', sa.Integer(), nullable=False, server_default='21'))
        batch_op.add_column(sa.Column('report_minute', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('report_minute')
        batch_op.drop_column('report_hour')

    # ### end Alembic commands ###
