"""add_show_balance_column

Revision ID: b1253de10124
Revises: 29301a8d8411
Create Date: 2026-02-13 16:36:27.410486

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1253de10124"
down_revision: str | Sequence[str] | None = "29301a8d8411"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("show_balance", sa.Boolean(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("show_balance")

    # ### end Alembic commands ###
